name: Create flows

on:
  workflow_call:
    secrets:
      google_credentials:
        required: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node dependencies
        run: npm ci
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          CREDENTIALS: ${{ secrets.google_credentials }}
        run: |
          python -m parenttext_pipeline.cli
          echo upload=${{ inputs.upload }}
      - name: Publish output folder
        uses: actions/upload-artifact@v4
        with:
          name: Output Files
          path: output
