name: Create flows
on:
  workflow_dispatch:
    inputs:
      upload:
        description: Upload flows to RapidPro
        type: boolean
        required: false
        default: false
      config_file:
        description: Choose which config file to run
        type: choice
        options:
          - china/config.py
          - malaysia/config.py
          - mexico/config.py
          - south_africa/config.py
        required: true
        
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node dependencies
        run: npm ci
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
        run: |
          python -m parenttext_pipeline.cli ${{ github.event.inputs.config_file }}
          echo upload=${{ inputs.upload }}
      - name: Publish output folder
        uses: actions/upload-artifact@v2
        with:
          name: Output Files
          path: output

